// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: leader.proto

package leader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LeaderServiceClient is the client API for LeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderServiceClient interface {
	// CreateTopic creates a new topic.
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	// DeleteTopic deletes a topic.
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error)
	// RecordLEO records the Log End Offset (LEO) of a replica.
	RecordLEO(ctx context.Context, in *RecordLEORequest, opts ...grpc.CallOption) (*RecordLEOResponse, error)
	// ReplicateStream streams log entries to replicas for replication.
	ReplicateStream(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (LeaderService_ReplicateStreamClient, error)
}

type leaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderServiceClient(cc grpc.ClientConnInterface) LeaderServiceClient {
	return &leaderServiceClient{cc}
}

func (c *leaderServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, "/leader.LeaderService/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderServiceClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error) {
	out := new(DeleteTopicResponse)
	err := c.cc.Invoke(ctx, "/leader.LeaderService/DeleteTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderServiceClient) RecordLEO(ctx context.Context, in *RecordLEORequest, opts ...grpc.CallOption) (*RecordLEOResponse, error) {
	out := new(RecordLEOResponse)
	err := c.cc.Invoke(ctx, "/leader.LeaderService/RecordLEO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderServiceClient) ReplicateStream(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (LeaderService_ReplicateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LeaderService_ServiceDesc.Streams[0], "/leader.LeaderService/ReplicateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &leaderServiceReplicateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LeaderService_ReplicateStreamClient interface {
	Recv() (*ReplicateResponse, error)
	grpc.ClientStream
}

type leaderServiceReplicateStreamClient struct {
	grpc.ClientStream
}

func (x *leaderServiceReplicateStreamClient) Recv() (*ReplicateResponse, error) {
	m := new(ReplicateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LeaderServiceServer is the server API for LeaderService service.
// All implementations must embed UnimplementedLeaderServiceServer
// for forward compatibility
type LeaderServiceServer interface {
	// CreateTopic creates a new topic.
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	// DeleteTopic deletes a topic.
	DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error)
	// RecordLEO records the Log End Offset (LEO) of a replica.
	RecordLEO(context.Context, *RecordLEORequest) (*RecordLEOResponse, error)
	// ReplicateStream streams log entries to replicas for replication.
	ReplicateStream(*ReplicateRequest, LeaderService_ReplicateStreamServer) error
	mustEmbedUnimplementedLeaderServiceServer()
}

// UnimplementedLeaderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeaderServiceServer struct {
}

func (UnimplementedLeaderServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedLeaderServiceServer) DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTopic not implemented")
}
func (UnimplementedLeaderServiceServer) RecordLEO(context.Context, *RecordLEORequest) (*RecordLEOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordLEO not implemented")
}
func (UnimplementedLeaderServiceServer) ReplicateStream(*ReplicateRequest, LeaderService_ReplicateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReplicateStream not implemented")
}
func (UnimplementedLeaderServiceServer) mustEmbedUnimplementedLeaderServiceServer() {}

// UnsafeLeaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderServiceServer will
// result in compilation errors.
type UnsafeLeaderServiceServer interface {
	mustEmbedUnimplementedLeaderServiceServer()
}

func RegisterLeaderServiceServer(s grpc.ServiceRegistrar, srv LeaderServiceServer) {
	s.RegisterService(&LeaderService_ServiceDesc, srv)
}

func _LeaderService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader.LeaderService/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderService_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader.LeaderService/DeleteTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderService_RecordLEO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordLEORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServiceServer).RecordLEO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader.LeaderService/RecordLEO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServiceServer).RecordLEO(ctx, req.(*RecordLEORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderService_ReplicateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplicateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaderServiceServer).ReplicateStream(m, &leaderServiceReplicateStreamServer{stream})
}

type LeaderService_ReplicateStreamServer interface {
	Send(*ReplicateResponse) error
	grpc.ServerStream
}

type leaderServiceReplicateStreamServer struct {
	grpc.ServerStream
}

func (x *leaderServiceReplicateStreamServer) Send(m *ReplicateResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LeaderService_ServiceDesc is the grpc.ServiceDesc for LeaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leader.LeaderService",
	HandlerType: (*LeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _LeaderService_CreateTopic_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _LeaderService_DeleteTopic_Handler,
		},
		{
			MethodName: "RecordLEO",
			Handler:    _LeaderService_RecordLEO_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReplicateStream",
			Handler:       _LeaderService_ReplicateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "leader.proto",
}
